In [6]:
from faker import Faker
import random
import pandas as pd

# Inicializa o Faker em pt-BR
fake = Faker('pt_BR')

# Lista de produtos fictícios e seus preços
produtos = [
    {"nome": "Notebook", "preco": 3500.00},
    {"nome": "Mouse", "preco": 50.00},
    {"nome": "Teclado", "preco": 120.00},
    {"nome": "Monitor", "preco": 950.00},
    {"nome": "Cadeira Gamer", "preco": 1400.00},
    {"nome": "Headset", "preco": 300.00},
    {"nome": "Webcam", "preco": 200.00}
]

# Lista de estados brasileiros (UFs)
estados = [
    'AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA',
    'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN',
    'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO'
]

# Quantidade de registros
num_registros = 100

# Lista para armazenar os dados
dados_vendas = []

# Geração dos dados de venda como ID do pedido, Data, Nome do cliente, Sexo e etc
for i in range(1, num_registros + 1):
    produto = random.choice(produtos)
    quantidade = random.randint(1, 5)
    preco_unitario = produto["preco"]
    total = round(preco_unitario * quantidade, 2)

    sexo = random.choice(['Masculino', 'Feminino'])
    if sexo == 'Masculino':
        nome = fake.name_male()
    else:
        nome = fake.name_female()

    estado = random.choice(estados)
    
    dados_vendas.append({
        "ID Pedido": f"PED{i:04d}",
        "Data da Venda": fake.date_between(start_date='-6M', end_date='today').strftime('%d/%m/%Y'),
        "Cliente": nome,
        "Sexo": sexo,
        "CPF": fake.cpf(),
        "Estado": estado,
        "Produto": produto["nome"],
        "Quantidade": quantidade,
        "Preço Unitário (R$)": round(preco_unitario, 2),
        "Total da Venda (R$)": total
    })

# Converte para DataFrame
df = pd.DataFrame(dados_vendas)

# Exibe os 5 primeiros
df.head()

# (Opcional) Salvar em Excel
# df.to_excel('dados_vendas_com_estado_e_sexo.xlsx')

,ID Pedido,Data da Venda,Cliente,Sexo,CPF,Estado,Produto,Quantidade,Preço Unitário (R$),Total da Venda (R$)
0,PED0001,02/01/2025,Francisco Marques,Masculino,274.918.503-32,MT,Webcam,2,200.0,400.0
1,PED0002,08/12/2024,Aylla Aparecida,Feminino,973.561.248-82,DF,Mouse,4,50.0,200.0
2,PED0003,20/02/2025,Srta. Anna Liz Fonseca,Feminino,463.192.078-50,MT,Headset,2,300.0,600.0
3,PED0004,29/03/2025,Vitor Gabriel Pereira,Masculino,079.351.286-77,RJ,Cadeira Gamer,3,1400.0,4200.0
4,PED0005,22/12/2024,Maria Alice Mendes,Feminino,675.302.198-12,SC,Cadeira Gamer,3,1400.0,4200.0